import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { BiRightArrowAlt } from "react-icons/bi";
import CountAchivement from 'components/incCounter/CountAchivement';
import Services from 'components/services/Services';
import About from 'components/about/About';
import UserFeedback from 'components/feedbackslider/UserFeedback';
import Project from 'components/projects/project';
import Contact from "@/components/contacts/contact";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ///////////////////////////////////////////////// */}

      <div className={styles.fluidcontainer}>
        <div className={styles.main1}>
          <p> We Provide Outsourced</p>
          <h1>IT Solution</h1>
          <p>IT producers worldwide face similar challenges around animal welfare, farm profitability, product and work efficiency.</p>
          <div className={styles.undermain}>
            <a href="https://www.google.com" target={"_blank"}><button className={`${styles.btn} flex items-center gap-3`}>Get Started <BiRightArrowAlt className={`${styles.arrow} text-2xl`} /></button></a>
          </div>
        </div>
        <div className={styles.container}>
          {/* <img src="/businessman-working-virtual-screen_53876-104333.webp" alt="" /> */}
        </div>
      </div>
      {/* ///////////////////////////////////////////////////////////////////////// */}

      <About id="about" />

      {/* ///////////////////////////////////////////////// */}

      <Services id="services" />

      {/* ///////////////////////////////////////////////// */}

      <UserFeedback />

      {/* ///////////////////////////////////////////////////////////////////////// */}
      <Project id="portfolio" />
      {/* /////////////////////////////////////////////////////////////////////// */}
      <CountAchivement />

      {/* <Contact /> */}
    </>
  )
}
